on:
  push:
    branches:    
      - master
name: Build
jobs:
  test:
    name: Build
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=12.4,name=iPhone X']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Remove pods
        run: rm -rf Pods
      - name: PodInstall
        run: pod install
      - name: remove DerivedData
        run: rm -rf Users/runner/Library/Developer/Xcode/DerivedData
      - name: Build
        run: |
            xcodebuild \
            -workspace Test4All.xcworkspace \
            -scheme Test4All \
            -destination "${destination}" \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
            clean test
        env:
         destination: ${{ matrix.destination }}
