on:
  push:
    branches:    
      - master
name: Build
jobs:
  test:
    name: Build
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator, id=8813E537-BE6C-429A-9CAC-E0428A50C93E, OS=12.4, name=iPhone 8']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        run: |
            xcodebuild \
            -workspace Test4All.xcworkspace \
            -scheme Test4All \
            -destination "${destination}" \
            clean test
        env:
         destination: ${{ matrix.destination }}
