on:
  push:
    branches:    
      - master
name: Build
jobs:
  test:
    name: Build
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform:iOS Simulator, id:5E0BE22C-A4F0-4CCF-A869-4C2E71F33844, OS:12.4, name:iPhone 6s']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        run: |
            xcodebuild clean build -workspace Test4All.xcworkspace -scheme Test4All -destination "platform:iOS Simulator, OS:12.4, name:iPhone 6s" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env:
         destination: ${{ matrix.destination }}
