on:
  push:
    branches:    
      - master
name: Build
jobs:
  test:
    name: Build
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform:iOS Simulator, id:5E0BE22C-A4F0-4CCF-A869-4C2E71F33844, OS:12.4, name:iPhone 6s']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        run: |
            xcodebuild \
            -workspace Test4All.xcworkspace \
            -scheme Test4All \
            -destination 'platform=iOS,id=5E0BE22C-A4F0-4CCF-A869-4C2E71F33844' \
            clean test
        env:
         destination: 'platform=iOS,id=5E0BE22C-A4F0-4CCF-A869-4C2E71F33844'
